{"users":{

		"admin_sjomphe":{	
			"name":"Stef",
			"lastname":"Jomphe",
			"password":"",
			"role":"admin"
		},
		"admin_tdumas":{	
			"name":"Thierry",
			"lastname":"dumas",
			"password":"",
			"role":"admin"
		},
		"rbeaumier":{	
			"name":"Robert",
			"lastname":"Beaumier",
			"password":"", 
			"role":"designer"
		},
		"jlevac":{	
			"name":"Julie",
			"lastname":"Levac",
			"password":"", 
			"role":"designer"
		},
		"ddion":{	
			"name":"David",
			"lastname":"Dion",
			"password":"", 
			"role":"manager"
		},
		"mlamontagne":{	
			"name":"Myriam",
			"lastname":"Lamontagne",
			"password":"", 
			"role":"manager"
		},
		"sbose":{	
			"name":"Subir",
			"lastname":"Bose",
			"password":"", 
			"role":"manager"
		},
		"cdaaboul":{	
			"name":"Charles",
			"lastname":"Daaboul",
			"password":"", 
			"role":"manager"
		},
		"admin_vtimbro":{	
			"name":"Vincent",
			"lastname":"Timbro",
			"password":"", 
			"role":"admin"
		},
			"mtremblay":{
				"name":"Melissa", 
				"lastname":"Tremblay",
				"password":"",
				"role":"reviewer"
		},
			"tdhillon":{
				"name":"Tejvanse", 
				"lastname":"Dhillon",
				"password":"",
				"role":"reviewer"
		},
			"":{
				"name":"Generic", 
				"lastname":"User",
				"password":"",
				"role":"admin"
		},
			"jbelisle":{
				"name":"Julie", 
				"lastname":"Bélisle-Boutet",
				"password":"",
				"role":"manager"
		},
			"jdeschatelets":{
				"name":"Josianne", 
				"lastname":"Deschatelets",
				"password":"",
				"role":"manager"
		},
			"blalonde":{
				"name":"Benoit", 
				"lastname":"Lalonde",
				"password":"",
				"role":"manager"
		}
	}
}